// mean/client/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  template: `
    <nav class="navbar">
      <div class="container nav-content">
        <a routerLink="/" class="logo">me</a>

        <div class="nav-links">
          <a routerLink="/feed" routerLinkActive="active">Feed</a>
          <a routerLink="/players" routerLinkActive="active">Players</a>
          <a routerLink="/leaderboard" routerLinkActive="active">Leaderboard</a>

          @if (authService.isAuthenticated()) {
            <a routerLink="/game" routerLinkActive="active">Game</a>
            <a routerLink="/profile" routerLinkActive="active">Profile</a>
            <button class="btn btn-secondary" (click)="authService.logout()">Logout</button>
          } @else {
            <a routerLink="/login" class="btn btn-secondary">Login</a>
            <a routerLink="/register" class="btn btn-primary">Sign Up</a>
          }
        </div>
      </div>
    </nav>
  `,
  styles: [`
    .navbar {
      background-color: var(--surface);
      border-bottom: 1px solid var(--border);
      height: 64px;
      display: flex;
      align-items: center;
    }

    .nav-content {
      display: flex;
      justify-content: space-between;
      align-items: center;
      width: 100%;
    }

    .logo {
      font-size: 1.5rem;
      font-weight: 700;
      color: var(--primary);
    }

    .logo:hover {
      text-decoration: none;
    }

    .nav-links {
      display: flex;
      align-items: center;
      gap: 1.5rem;
    }

    .nav-links a:not(.btn) {
      color: var(--text-secondary);
      font-weight: 500;
      transition: color 0.2s;
    }

    .nav-links a:not(.btn):hover,
    .nav-links a:not(.btn).active {
      color: var(--primary);
      text-decoration: none;
    }
  `]
})
export class NavbarComponent {
  constructor(public authService: AuthService) {}
}

// app/components/NavBar.tsx
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../lib/AuthContext";

export function NavBar() {
  const { isAuthenticated, user, logout, isLoading } = useAuth();
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    navigate('/');
  };

  if (isLoading) {
    return <header className="bg-gray-800 text-white p-4 h-[68px]"></header> // Placeholder for height
  }

  return (
    <header className="bg-gray-800 text-white p-4">
      <nav className="container mx-auto flex justify-between items-center">
        <Link to="/" className="text-2xl font-bold text-white">
          SocialRPG
        </Link>
        <div className="flex space-x-8">
          {/* Social Section */}
          <div className="flex items-center space-x-4">
            <span className="font-semibold">Social</span>
            <Link to="/feed" className="hover:text-gray-300">Feed</Link>
            <Link to="/friends" className="hover:text-gray-300">Friends</Link>
            <Link to="/groups" className="hover:text-gray-300">Groups</Link>
            <Link to="/messages" className="hover:text-gray-300">Messages</Link>
          </div>

          <div className="border-l border-gray-600 h-6 self-center"></div>

          {/* Game Section */}
          <div className="flex items-center space-x-4">
            <span className="font-semibold">Game</span>
            <Link to="/game/dashboard" className="hover:text-gray-300">Dashboard</Link>
            <Link to="/game/players" className="hover:text-gray-300">Find Battle</Link>
            <Link to="/game/leaderboard" className="hover:text-gray-300">Leaderboard</Link>
          </div>
        </div>

        {/* User Profile / Auth */}
        <div className="flex items-center space-x-4">
          {isAuthenticated ? (
            <>
              <Link to="/profile/me" className="hover:text-gray-300">Welcome, {user?.username}</Link>
              <button onClick={handleLogout} className="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded">Logout</button>
            </>
          ) : (
            <>
              <Link to="/login" className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">Login</Link>
              <Link to="/register" className="bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded">Register</Link>
            </>
          )}
        </div>
      </nav>
    </header>
  );
}
